// components/TicketList.vue
<template>
  <div class="space-y-3">
    <h2 class="mb-4 text-slate-800 dark:text-slate-200">Recent Tickets</h2>
    <div class="space-y-3 max-h-[calc(100vh-300px)] overflow-y-auto pr-2">
      <TicketCard
        v-for="ticket in tickets"
        :key="ticket.id"
        :ticket="ticket"
        :isSelected="selectedTicketId === ticket.id"
        @click="$emit('ticket-select', ticket.id)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import TicketCard from './TicketCard.vue'

interface Ticket {
  id: string
  title: string
  status: 'open' | 'in-progress' | 'closed'
  priority: 'low' | 'medium' | 'high'
  date: string
  assignee: { name: string; avatar: string }
  description: string
}

interface Props {
  tickets: Ticket[]
  selectedTicketId: string | null
}

defineProps<Props>()

defineEmits<{
  'ticket-select': [ticketId: string]
}>()
</script>

// components/TicketList.tsx
import { TicketCard } from "./TicketCard";

interface Ticket {
  id: string;
  title: string;
  status: 'open' | 'in-progress' | 'closed';
  priority: 'low' | 'medium' | 'high';
  date: string;
  assignee: { name: string; avatar: string };
  description: string;
}

interface TicketListProps {
  tickets: Ticket[];
  selectedTicketId: string | null;
  onTicketSelect: (ticketId: string) => void;
}

export function TicketList({ tickets, selectedTicketId, onTicketSelect }: TicketListProps) {
  return (
    <div className="space-y-3">
      <h2 className="mb-4">Recent Tickets</h2>
      <div className="space-y-3 max-h-[calc(100vh-300px)] overflow-y-auto pr-2">
        {tickets.map((ticket) => (
          <TicketCard
            key={ticket.id}
            ticket={ticket}
            isSelected={selectedTicketId === ticket.id}
            onClick={() => onTicketSelect(ticket.id)}
          />
        ))}
      </div>
    </div>
  );
}
